{
	"json": {
		"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d"
	},
	"assemblyName": "EntityFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
	"className": "EntityFramework.Entity",
	"components": [{
		"json": {
			"parent": {
				"guid": "8a998fc1-8c6d-43de-8610-f9a77adbd785"
			},
			"entity": {
				"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d",
			},
			"guid": "24d5476a-e3a1-43ac-aecb-f2ff7a0e3d86",
		},
		"assemblyName": "EntityFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
		"className": "EntityFramework.Components.ChildrenComponent",
	}, {
		"json": {
			"groups": ["save", ],
			"entity": {
				"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d",
			},
			"guid": "558ac35d-1f63-4bab-94f1-f31db261adcf",
		},
		"assemblyName": "EntityFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
		"className": "EntityFramework.Components.GroupComponent",
	}, {
		"json": {
			"name": "win",
			"entity": {
				"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d",
			},
			"guid": "2e450d48-5b42-47a4-b648-22dff2530690",
		},
		"assemblyName": "EntityFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
		"className": "EntityFramework.Components.TagComponent",
	}, {
		"json": {
			"win": "False",
			"entity": {
				"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d",
			},
			"guid": "c8d372eb-d5f3-4142-908d-8ddf77dc4968",
		},
		"assemblyName": "EntityEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
		"className": "EntityEngine.Components.WinComponent",
	}, {
		"json": {
			"rotationXMatrix": {
				"M11": "1",
				"M12": "0",
				"M13": "0",
				"M14": "0",
				"M21": "0",
				"M22": "1",
				"M23": "0",
				"M24": "0",
				"M31": "0",
				"M32": "0",
				"M33": "1",
				"M34": "0",
				"M41": "0",
				"M42": "0",
				"M43": "0",
				"M44": "1",
				"Up": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Down": {
					"X": "0",
					"Y": "-1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Right": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Left": {
					"X": "-1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Forward": {
					"X": "0",
					"Y": "0",
					"Z": "-1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Backward": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"TranslationVector": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "False",
					"IsZero": "True",
				},
				"ScaleVector": {
					"X": "1",
					"Y": "1",
					"Z": "1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"IsIdentity": "True",
			},
			"rotationYMatrix": {
				"M11": "-1",
				"M12": "0",
				"M13": "8.742278E-08",
				"M14": "0",
				"M21": "0",
				"M22": "1",
				"M23": "0",
				"M24": "0",
				"M31": "-8.742278E-08",
				"M32": "0",
				"M33": "-1",
				"M34": "0",
				"M41": "0",
				"M42": "0",
				"M43": "0",
				"M44": "1",
				"Up": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Down": {
					"X": "0",
					"Y": "-1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Right": {
					"X": "-1",
					"Y": "0",
					"Z": "8.742278E-08",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Left": {
					"X": "1",
					"Y": "0",
					"Z": "-8.742278E-08",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Forward": {
					"X": "8.742278E-08",
					"Y": "0",
					"Z": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Backward": {
					"X": "-8.742278E-08",
					"Y": "0",
					"Z": "-1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row1": {
					"X": "-1",
					"Y": "0",
					"Z": "8.742278E-08",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row3": {
					"X": "-8.742278E-08",
					"Y": "0",
					"Z": "-1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column1": {
					"X": "-1",
					"Y": "0",
					"Z": "-8.742278E-08",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column3": {
					"X": "8.742278E-08",
					"Y": "0",
					"Z": "-1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"TranslationVector": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "False",
					"IsZero": "True",
				},
				"ScaleVector": {
					"X": "-1",
					"Y": "1",
					"Z": "-1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"IsIdentity": "False",
			},
			"rotationZMatrix": {
				"M11": "1",
				"M12": "0",
				"M13": "0",
				"M14": "0",
				"M21": "0",
				"M22": "1",
				"M23": "0",
				"M24": "0",
				"M31": "0",
				"M32": "0",
				"M33": "1",
				"M34": "0",
				"M41": "0",
				"M42": "0",
				"M43": "0",
				"M44": "1",
				"Up": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Down": {
					"X": "0",
					"Y": "-1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Right": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Left": {
					"X": "-1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Forward": {
					"X": "0",
					"Y": "0",
					"Z": "-1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Backward": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"TranslationVector": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "False",
					"IsZero": "True",
				},
				"ScaleVector": {
					"X": "1",
					"Y": "1",
					"Z": "1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"IsIdentity": "True",
			},
			"scalingMatrix": {
				"M11": "1",
				"M12": "0",
				"M13": "0",
				"M14": "0",
				"M21": "0",
				"M22": "1",
				"M23": "0",
				"M24": "0",
				"M31": "0",
				"M32": "0",
				"M33": "1",
				"M34": "0",
				"M41": "0",
				"M42": "0",
				"M43": "0",
				"M44": "1",
				"Up": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Down": {
					"X": "0",
					"Y": "-1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Right": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Left": {
					"X": "-1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Forward": {
					"X": "0",
					"Y": "0",
					"Z": "-1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Backward": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"TranslationVector": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "False",
					"IsZero": "True",
				},
				"ScaleVector": {
					"X": "1",
					"Y": "1",
					"Z": "1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"IsIdentity": "True",
			},
			"translationLocalMatrix": {
				"M11": "1",
				"M12": "0",
				"M13": "0",
				"M14": "0",
				"M21": "0",
				"M22": "1",
				"M23": "0",
				"M24": "0",
				"M31": "0",
				"M32": "0",
				"M33": "1",
				"M34": "0",
				"M41": "0",
				"M42": "0",
				"M43": "0",
				"M44": "1",
				"Up": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Down": {
					"X": "0",
					"Y": "-1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Right": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Left": {
					"X": "-1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Forward": {
					"X": "0",
					"Y": "0",
					"Z": "-1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Backward": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"TranslationVector": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "False",
					"IsZero": "True",
				},
				"ScaleVector": {
					"X": "1",
					"Y": "1",
					"Z": "1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"IsIdentity": "True",
			},
			"translationWorldMatrix": {
				"M11": "1",
				"M12": "0",
				"M13": "0",
				"M14": "0",
				"M21": "0",
				"M22": "1",
				"M23": "0",
				"M24": "0",
				"M31": "0",
				"M32": "0",
				"M33": "1",
				"M34": "0",
				"M41": "2",
				"M42": "2",
				"M43": "0",
				"M44": "1",
				"Up": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Down": {
					"X": "0",
					"Y": "-1",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Right": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Left": {
					"X": "-1",
					"Y": "0",
					"Z": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Forward": {
					"X": "0",
					"Y": "0",
					"Z": "-1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Backward": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Row4": {
					"X": "2",
					"Y": "2",
					"Z": "0",
					"W": "1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"Column1": {
					"X": "1",
					"Y": "0",
					"Z": "0",
					"W": "2",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"Column2": {
					"X": "0",
					"Y": "1",
					"Z": "0",
					"W": "2",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"Column3": {
					"X": "0",
					"Y": "0",
					"Z": "1",
					"W": "0",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"Column4": {
					"X": "0",
					"Y": "0",
					"Z": "0",
					"W": "1",
					"IsNormalized": "True",
					"IsZero": "False",
				},
				"TranslationVector": {
					"X": "2",
					"Y": "2",
					"Z": "0",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"ScaleVector": {
					"X": "1",
					"Y": "1",
					"Z": "1",
					"IsNormalized": "False",
					"IsZero": "False",
				},
				"IsIdentity": "False",
			},
			"entity": {
				"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d",
			},
			"guid": "a21712e8-3131-4bf5-ba98-4f999f3faf5e",
		},
		"assemblyName": "EntityEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
		"className": "EntityEngine.Components.PositionComponent",
	}, {
		"json": {
			"renderFlags": "0",
			"mesh": {
				"guid": "bc02a3c7-9276-4a44-8cf2-3042f19f136d",
				"filePath": "Maps/Test/Models/square.mesh",
			},
			"shader": {
				"guid": "f8b75257-cb5e-4087-866b-9b5cf1d48486",
				"filePath": "Maps/Test/Shaders/basicEffect.fx",
				"shaderVars": [{
					"SemanticName": "POSITION",
					"SemanticIndex": "0",
					"Format": "6",
					"Slot": "0",
					"AlignedByteOffset": "0",
					"Classification": "0",
					"InstanceDataStepRate": "0",
				}, ],
				"shaderLevel": "fx_4_0",
			},
			"entity": {
				"guid": "509e33f8-d85e-4b6f-864b-cc76af32ea9d",
			},
			"guid": "061f9d20-1ffc-45b1-97e0-d9e29dbe0717",
		},
		"assemblyName": "EntityEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
		"className": "EntityEngine.Components.RenderComponent",
	}, ],
}